// Ad configuration — generated by build.sh from environment variables.
// Do not edit manually in production; values are injected at deploy time.
window.ADS_CONFIG = {
    provider: "none",
    adsterra: {
        top:       { src: "", containerId: "" },
        inArticle: { src: "", containerId: "" },
        bottom:    { src: "", containerId: "" },
        left:      { src: "", containerId: "" },
        right:     { src: "", containerId: "" }
    }
};
